
services:
  metoc_agent:
    build:
      context: ./agents/metoc_agent
    image: metoc_agent:latest
    container_name: metoc_agent
    ports:
      - "8080:8080"
    env_file: ./.env.sh


  seaice_agent:
    build:
      context: ./agents/seaice_agent
    image: seaice_agent:latest
    container_name: seaice_agent
    ports:
      - "8090:8090"
    env_file: ./.env.sh
    volumes:
      - /home/vpcuser/agents/data:/home/vpcuser/agents/data

  ais_agent:
    build:
      context: ./agents/ais_agent
    image: ais_agent:latest
    container_name: ais_agent
    ports:
      - "8100:8100"
    env_file: ./.env.sh

  ports_agent:
    build:
      context: ./agents/ports_agent
    image: ports_agent:latest
    container_name: ports_agent
    ports:
      - "8110:8110"
    env_file: ./.env.sh
    
  map_agent:
    build:
      context: ./agents/map_agent
    image: map_agent:latest
    container_name: map_agent
    ports:
      - "8120:8120"
    env_file: ./.env.sh


  postgres:
    image: postgres:15
    container_name: langfuse-db
    restart: always
    environment:
      POSTGRES_USER: langfuse
      POSTGRES_PASSWORD: langfusepass
      POSTGRES_DB: langfuse
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  langfuse:
    image: langfuse/langfuse:latest
    container_name: langfuse-app
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://langfuse:langfusepass@postgres:5432/langfuse
      NEXTAUTH_SECRET: supersecretkey
    ports:
      - "3000:3000"

secrets:
  env:
    file: ./.env.sh


volumes:
  pgdata:
