
services:
  metoc_agent:
    build:
      context: ./metoc_agent
    image: metoc_agent:latest
    container_name: metoc_agent
    ports:
      - "8080:8080"
    env_file: ./.env.sh


  seaice_agent:
    build:
      context: ./seaice_agent
    image: seaice_agent:latest
    container_name: seaice_agent
    ports:
      - "8090:8090"
    env_file: ./.env.sh
    volumes:
      - /home/vpcuser/agents/data:/home/vpcuser/agents/data

  ais_agent:
    build:
      context: ./ais_agent
    image: ais_agent:latest
    container_name: ais_agent
    ports:
      - "8100:8100"
    env_file: ./.env.sh

  ports_agent:
    build:
      context: ./ports_agent
    image: ports_agent:latest
    container_name: ports_agent
    ports:
      - "8110:8110"
    env_file: ./.env.sh
    
  map_agent:
    build:
      context: ./map_agent
    image: map_agent:latest
    container_name: map_agent
    ports:
      - "8120:8120"
    env_file: ./.env.sh

secrets:
  env:
    file: ./.env.sh

