openapi: 3.1.0
info:
  title: api_gateway_agent
  description: AIS gateway with AOI registry and governance meta (FQ URLs).
  version: 0.2.0
paths:
  /health:
    get:
      tags:
      - Health
      summary: Health
      operationId: health_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /aoi:
    get:
      tags:
      - AOI
      summary: List Aois
      operationId: list_aois_aoi_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /aoi/{aoi_id}:
    get:
      tags:
      - AOI
      summary: Get Aoi
      operationId: get_aoi_aoi__aoi_id__get
      parameters:
      - name: aoi_id
        in: path
        required: true
        schema:
          type: string
          description: AOI identifier
          title: Aoi Id
        description: AOI identifier
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /vessels/search:
    get:
      tags:
      - Vessels
      summary: Vessels Search
      operationId: vessels_search_vessels_search_get
      parameters:
      - name: shipname
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Vessel name (full or partial)
          title: Shipname
        description: Vessel name (full or partial)
      - name: mmsi
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Maritime Mobile Service Identity
          title: Mmsi
        description: Maritime Mobile Service Identity
      - name: imo
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: IMO number
          title: Imo
        description: IMO number
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /vessels/aoi:
    get:
      tags:
      - Vessels
      summary: Vessels In Aoi
      operationId: vessels_in_aoi_vessels_aoi_get
      parameters:
      - name: aoi_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Registered AOI id; alternative to bbox
          title: Aoi Id
        description: Registered AOI id; alternative to bbox
      - name: bbox
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: minLon,minLat,maxLon,maxLat (WGS84)
          title: Bbox
        description: minLon,minLat,maxLon,maxLat (WGS84)
      - name: timespan
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          description: Minutes back
          default: 60
          title: Timespan
        description: Minutes back
      - name: shiptype
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: 2=fishing, 4=high_speed, 6=passenger, 7=cargo, 8=tanker
          title: Shiptype
        description: 2=fishing, 4=high_speed, 6=passenger, 7=cargo, 8=tanker
      - name: msgtype
        in: query
        required: false
        schema:
          type: string
          description: simple | extended | full
          default: simple
          title: Msgtype
        description: simple | extended | full
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /vessels/nearby:
    get:
      tags:
      - Vessels
      summary: Vessels Nearby
      operationId: vessels_nearby_vessels_nearby_get
      parameters:
      - name: lat
        in: query
        required: false
        schema:
          anyOf:
          - type: number
            maximum: 90.0
            minimum: -90.0
          - type: 'null'
          description: Latitude (WGS84)
          title: Lat
        description: Latitude (WGS84)
      - name: lon
        in: query
        required: false
        schema:
          anyOf:
          - type: number
            maximum: 180.0
            minimum: -180.0
          - type: 'null'
          description: Longitude (WGS84)
          title: Lon
        description: Longitude (WGS84)
      - name: radius_nm
        in: query
        required: false
        schema:
          type: number
          maximum: 1000.0
          exclusiveMinimum: 0.0
          description: Radius in nautical miles
          default: 50.0
          title: Radius Nm
        description: Radius in nautical miles
      - name: aoi_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: If provided (bbox AOI), its centroid is used
          title: Aoi Id
        description: If provided (bbox AOI), its centroid is used
      - name: timespan
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          description: Minutes back
          default: 60
          title: Timespan
        description: Minutes back
      - name: shiptype
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: 2=fishing, 4=high_speed, 6=passenger, 7=cargo, 8=tanker
          title: Shiptype
        description: 2=fishing, 4=high_speed, 6=passenger, 7=cargo, 8=tanker
      - name: msgtype
        in: query
        required: false
        schema:
          type: string
          description: simple | extended | full
          default: simple
          title: Msgtype
        description: simple | extended | full
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /vessel/info:
    get:
      tags:
      - Vessels
      summary: Vessel Info
      operationId: vessel_info_vessel_info_get
      parameters:
      - name: ship_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Provider vessel id
          title: Ship Id
        description: Provider vessel id
      - name: mmsi
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Maritime Mobile Service Identity
          title: Mmsi
        description: Maritime Mobile Service Identity
      - name: imo
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: IMO number
          title: Imo
        description: IMO number
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /vessel/photo:
    get:
      tags:
      - Vessels
      summary: Vessel Photo
      operationId: vessel_photo_vessel_photo_get
      parameters:
      - name: ship_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Provide vessel id
          title: Ship Id
        description: Provide vessel id
      - name: mmsi
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Maritime Mobile Service Identity
          title: Mmsi
        description: Maritime Mobile Service Identity
      - name: imo
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: IMO number
          title: Imo
        description: IMO number
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /vessel/track:
    get:
      tags:
      - Tracks
      summary: Vessel Track
      operationId: vessel_track_vessel_track_get
      parameters:
      - name: ship_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Provider vessel id
          title: Ship Id
        description: Provider vessel id
      - name: mmsi
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Maritime Mobile Service Identity
          title: Mmsi
        description: Maritime Mobile Service Identity
      - name: imo
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: IMO number
          title: Imo
        description: IMO number
      - name: fromdt
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: UTC start, e.g., 2025-09-01 00:00
          title: Fromdt
        description: UTC start, e.g., 2025-09-01 00:00
      - name: todt
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: UTC end, e.g., 2025-09-02 00:00
          title: Todt
        description: UTC end, e.g., 2025-09-02 00:00
      - name: timespan
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          description: Minutes back (alternative to from/todt)
          title: Timespan
        description: Minutes back (alternative to from/todt)
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
