
openapi: 3.0.3
info:
  title: NSIDC Sea Ice Agent API (Runtime Fetch)
  version: "0.4.0"
servers:
  - url: /
paths:
  /seaice/health:
    get:
      summary: Health check and configuration info
      responses:
        '200':
          description: Service health
          headers:
            X-Request-ID:
              description: Correlation ID assigned by middleware (or supplied by caller).
              schema: { type: string }
            X-Response-Time-MS:
              description: Elapsed processing time in milliseconds.
              schema: { type: string }
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string }
                  variable: { type: string }
                  crs: { type: string }
                  data_dir: { type: string }
                  url_pattern: { type: string }
                  sensors_tried:
                    type: array
                    items: { type: string }
                  governance:
                    $ref: '#/components/schemas/GovernanceMeta'

  /seaice/wms:
    get:
      summary: Returns a WMS URL template and example parameters
      parameters:
        - in: query
          name: layer
          schema: { type: string }
        - in: query
          name: time
          schema: { type: string, example: "YYYY-MM-DD" }
        - in: query
          name: bbox
          schema: { type: string, example: "60,-180,90,180" }
        - in: query
          name: srs
          schema: { type: string, default: "EPSG:4326" }
        - in: query
          name: width
          schema: { type: integer, default: 1024 }
        - in: query
          name: height
          schema: { type: integer, default: 512 }
      responses:
        '200':
          description: WMS template
          headers:
            X-Request-ID:
              description: Correlation ID assigned by middleware (or supplied by caller).
              schema: { type: string }
            X-Response-Time-MS:
              description: Elapsed processing time in milliseconds.
              schema: { type: string }
          content:
            application/json:
              schema:
                type: object
                properties:
                  wms_url_template: { type: string }
                  params_example:
                    type: object
                    additionalProperties: true
                  note: { type: string }
                  governance:
                    $ref: '#/components/schemas/GovernanceMeta'

  /seaice/download:
    get:
      summary: Ensure dataset for a date is cached locally (download if needed)
      parameters:
        - in: query
          name: time
          required: true
          schema:
            type: string
            pattern: '^\d{4}-\d{2}-\d{2}$'
        - in: query
          name: force
          schema: { type: boolean, default: false }
      responses:
        '200':
          description: Download (or cached) result
          headers:
            X-Request-ID:
              description: Correlation ID assigned by middleware (or supplied by caller).
              schema: { type: string }
            X-Response-Time-MS:
              description: Elapsed processing time in milliseconds.
              schema: { type: string }
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, enum: [cached, downloaded] }
                  time: { type: string }
                  sensor: { type: string }
                  url: { type: string }
                  file: { type: string }
                  size_bytes: { type: integer }
                  cache_cleared: { type: boolean }
                  governance:
                    $ref: '#/components/schemas/GovernanceMeta'

  /seaice/point:
    get:
      summary: Nearest-neighbor sample at a lat/lon (WGS84) for a date
      parameters:
        - in: query
          name: lat
          required: true
          schema: { type: number, minimum: -90, maximum: 90 }
        - in: query
          name: lon
          required: true
          schema: { type: number, minimum: -180, maximum: 180 }
        - in: query
          name: time
          schema: { type: string, example: "YYYY-MM-DD" }
      responses:
        '200':
          description: Point sample
          headers:
            X-Request-ID:
              description: Correlation ID assigned by middleware (or supplied by caller).
              schema: { type: string }
            X-Response-Time-MS:
              description: Elapsed processing time in milliseconds.
              schema: { type: string }
          content:
            application/json:
              schema:
                type: object
                properties:
                  lat: { type: number }
                  lon: { type: number }
                  time: { type: string }
                  value_raw: { type: number }
                  value_fraction: { type: number }
                  file: { type: string }
                  variable: { type: string }
                  projection: { type: string }
                  sensor: { type: string }
                  governance:
                    $ref: '#/components/schemas/GovernanceMeta'

  /seaice/stats:
    post:
      summary: Simple stats over a lat/lon bbox for a date
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [bbox]
              properties:
                bbox:
                  type: array
                  minItems: 4
                  maxItems: 4
                  items: { type: number }
                  example: [60, -180, 90, 180]
                time:
                  type: string
                  example: "YYYY-MM-DD"
      responses:
        '200':
          description: Stats
          headers:
            X-Request-ID:
              description: Correlation ID assigned by middleware (or supplied by caller).
              schema: { type: string }
            X-Response-Time-MS:
              description: Elapsed processing time in milliseconds.
              schema: { type: string }
          content:
            application/json:
              schema:
                type: object
                properties:
                  bbox:
                    type: array
                    items: { type: number }
                  time: { type: string }
                  count: { type: integer }
                  mean: { type: number }
                  median: { type: number }
                  min: { type: number }
                  max: { type: number }
                  units: { type: string, example: "fraction" }
                  file: { type: string }
                  variable: { type: string }
                  projection: { type: string }
                  sensor: { type: string }
                  governance:
                    $ref: '#/components/schemas/GovernanceMeta'

components:
  schemas:
    GovernanceMeta:
      type: object
      additionalProperties: true
      properties:
        app: { type: string }
        app_version: { type: string }
        endpoint: { type: string }
        timestamp: { type: string, format: date-time }
        request_id: { type: string }
        served_by: { type: string }
        inputs:
          type: object
          additionalProperties: true
        data_lineage:
          type: object
          additionalProperties: true
        quality:
          type: object
          additionalProperties: true
        policies_applied:
          type: array
          items: { type: string }
        risk_assessments:
          type: array
          items:
            type: object
            additionalProperties: true
        tags:
          type: object
          additionalProperties: true
        license:
          type: object
          properties:
            name: { type: string }
            url: { type: string }
